[package]
name = "ferrodoc-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ferrodoc-core = { path = "../ferrodoc-core" }
ferrodoc-engine-api = { path = "../ferrodoc-engine-api" }
schemars.workspace = true
serde.workspace = true
