[package]
name = "ferrodoc-foundry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
ferrodoc-core = { path = "../ferrodoc-core" }
font8x8.workspace = true
image.workspace = true
rand.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
