[package]
name = "ferrodoc-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
ferrodoc-core = { path = "../ferrodoc-core" }
ferrodoc-foundry = { path = "../ferrodoc-foundry" }
ferrodoc-ir = { path = "../ferrodoc-ir" }
regex.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
