[package]
name = "ferrodoc-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ferrodoc-ir = { path = "../ferrodoc-ir" }
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
